name: "Setup Basic CI Pipeline"

on:
    push:
        branches:
            - main
    
    pull_request:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: "Setup NodeJs"
              uses: actions/setup-node@v7
              with:
                node-version: 24

            - name: "Check Node Version"
              run: node --version

            - name: "Cloning The Repo"
              uses: actions/checkout@v6

            - name: "Installing Dependencies"
              run: npm install

            - name: "Run Lint"
              run: npm run lint

            - name: "Run build"
              run: npm run build

            - name: "Upload product-ready build files"
              uses: actions/upload-artifact@v4
              with:
                name: build
                path: dist/

